export interface Product {
  id: string;
  name: string;
  slug: string;
  shortDescription: string;
  description: string;
  format: string;
  price: number;
  image: string;
  category: string;
  batchDataAvailable: boolean;
  seoTitle?: string;
  metaDescription?: string;
}

export const products: Product[] = [
  {
    id: '5',
    name: '10ml Bacteriostatic Mixing Water',
    slug: '10ml-bacteriostatic-mixing-water',
    shortDescription: 'USP-grade sterile mixing solution for laboratory research and analytical testing.',
    description: 'High-purity 10ml Bacteriostatic Mixing Water, filtered and sterile-processed for laboratory research. Essential for the reconstitution of lyophilized peptides in controlled scientific settings. This product is strictly for research purposes.',
    format: 'Sterile Solution',
    price: 5.95,
    image: '/products/10ml-bacteriostatic-mixing-water.png',
    category: 'Peptides',
    batchDataAvailable: true,
    seoTitle: 'Buy 10ml Bacteriostatic Mixing Water UK | USP Grade Research Solution',
    metaDescription: 'Purchase 10ml Bacteriostatic Mixing Water for laboratory research. Sterile-processed, USP-grade solution for analytical testing. Same-day UK dispatch.'
  },
  {
    id: '6',
    name: 'BPC-157 5mg',
    slug: 'bpc-157-5mg',
    shortDescription: 'High-purity Pentadecapeptide BPC-157 for in-vitro laboratory research.',
    description: 'BPC-157 (Body Protection Compound 157) 5mg is supplied as a high-purity lyophilized powder. Verified via HPLC to exceed 99% purity, this synthetic pentadecapeptide is designed for analytical testing and biochemical research. Strictly for research use only.',
    format: 'Lyophilized Powder',
    price: 16.95,
    image: '/products/bpc-157-5mg.png',
    category: 'Peptides',
    batchDataAvailable: true,
    seoTitle: 'BPC-157 5mg Peptide UK | 99% HPLC Purity | Research Only',
    metaDescription: 'Buy BPC-157 5mg research peptide in the UK. 99%+ HPLC verified purity, lyophilized for stability. Third-party COA available. Fast, tracked UK shipping.'
  },
  {
    id: '7',
    name: 'Thymosin Beta 4 5mg TB500',
    slug: 'thymosin-beta-4-5mg-tb500',
    shortDescription: '99% Purity TB-500 (Thymosin Beta-4) 5mg for scientific research applications.',
    description: 'Thymosin Beta-4 (TB-500) 5mg is a synthetic version of the naturally occurring peptide. Our laboratory-grade TB-500 is lyophilized for maximum stability and verified for high purity through mass spectrometry and HPLC analysis. Research use only.',
    format: 'Lyophilized Powder',
    price: 33,
    image: '/products/thymosin-beta-4-5mg-tb500.png',
    category: 'Peptides',
    batchDataAvailable: true,
    seoTitle: 'Buy TB-500 (Thymosin Beta 4) 5mg UK | High Purity Peptides',
    metaDescription: 'Premium TB-500 5mg research peptide. Laboratory-grade lyophilized Thymosin Beta 4 with 99% purity. HPLC verified. Reliable UK laboratory material supplier.'
  },
  {
    id: '8',
    name: 'CJC-1295 MOD GRF 1-29 / without DAC 2mg',
    slug: 'cjc-1295-mod-grf-1-29-without-dac-2mg',
    shortDescription: 'Modified GRF (1-29) 2mg high-purity peptide for analytical research.',
    description: 'CJC-1295 without DAC (also known as Modified GRF 1-29) 2mg is a synthetic analog of growth hormone-releasing hormone. Supplied as a stable lyophilized cake, verified for high chemical purity and molecular weight consistency. For laboratory research only.',
    format: 'Lyophilized Powder',
    price: 12.95,
    image: '/products/cjc-1295-mod-grf-1-29-without-dac-2mg.png',
    category: 'Peptides',
    batchDataAvailable: true,
    seoTitle: 'CJC-1295 MOD GRF 1-29 2mg UK | 99% Purity Research Peptide',
    metaDescription: 'High-purity CJC-1295 (Modified GRF 1-29) 2mg. No DAC. Lyophilized for research stability. HPLC tested. Fast UK dispatch from RetaPharma.'
  },
  {
    id: '9',
    name: 'Ipamorelin 2mg',
    slug: 'ipamorelin-2mg',
    shortDescription: 'High-purity Ipamorelin 2mg lyophilized peptide for biochemical research.',
    description: 'Ipamorelin 2mg is a selective growth hormone secretagogue and ghrelin receptor agonist. Our production process ensures a purity level of 99%+, validated by 3rd party laboratory COAs. For in-vitro scientific research and testing only.',
    format: 'Lyophilized Powder',
    price: 9.95,
    image: '/products/ipamorelin-2mg.png',
    category: 'Peptides',
    batchDataAvailable: true,
    seoTitle: 'Buy Ipamorelin 2mg UK | Lab-Tested Research Peptide',
    metaDescription: 'Premium Ipamorelin 2mg peptide. 99% HPLC purity verified. Lyophilized research-grade material. Secure ordering and fast UK delivery. Research use only.'
  },
  {
    id: '10',
    name: 'Thymosin Beta 4 2mg (TB500)',
    slug: 'thymosin-beta-4-2mg-tb500',
    shortDescription: 'Research-grade TB-500 2mg for laboratory stability and purity testing.',
    description: 'Thymosin Beta-4 (TB-500) 2mg supplied in a lyophilized vial. This synthetic peptide is produced to rigorous laboratory standards, ensuring high bio-identity and chemical purity for scientific research applications. Research use only.',
    format: 'Lyophilized Powder',
    price: 16.95,
    image: '/products/thymosin-beta-4-2mg-tb500.png',
    category: 'Peptides',
    batchDataAvailable: true,
    seoTitle: 'TB-500 2mg Peptide UK | Thymosin Beta 4 Research Grade',
    metaDescription: 'High-purity TB-500 (Thymosin Beta 4) 2mg. Lyophilized research peptide with verified HPLC purity. Reliable UK dispatch and cold-chain storage.'
  },
  {
    id: '11',
    name: 'GHRP-6 5mg',
    slug: 'ghrp-6-5mg',
    shortDescription: 'Growth Hormone Releasing Peptide-6 5mg for scientific research.',
    description: 'GHRP-6 (Growth Hormone Releasing Peptide-6) 5mg is a synthetic hexapeptide. Our laboratory-grade GHRP-6 is purified to >99% via HPLC, ensuring reliable data for biochemical research and receptor affinity studies. Strictly for research use.',
    format: 'Lyophilized Powder',
    price: 9.95,
    image: '/products/ghrp-6-5mg.png',
    category: 'Peptides',
    batchDataAvailable: true,
    seoTitle: 'GHRP-6 5mg Peptide UK | Buy High Purity Research Peptides',
    metaDescription: 'Laboratory-grade GHRP-6 5mg. 99% HPLC verified purity. Lyophilized powder for research stability. Fast, tracked UK shipping. For research purposes only.'
  },
  {
    id: '12',
    name: 'GHRP-2 5mg',
    slug: 'ghrp-2-5mg',
    shortDescription: '99%+ Purity GHRP-2 5mg peptide for analytical and biochemical testing.',
    description: 'GHRP-2 (Growth Hormone Releasing Peptide-2) 5mg is a potent synthetic agonist of the ghrelin receptor. Sourced for high purity and consistent molecular weight, this research-grade material is suitable for varied laboratory applications. Research use only.',
    format: 'Lyophilized Powder',
    price: 9.95,
    image: '/products/ghrp-2-5mg.png',
    category: 'Peptides',
    batchDataAvailable: true,
    seoTitle: 'Buy GHRP-2 5mg UK | Laboratory Grade Research Peptides',
    metaDescription: 'Premium GHRP-2 5mg research peptide. 99%+ HPLC purity. Lyophilized for long-term stability. Fast UK delivery from RetaPharma UK.'
  },
  {
    id: '13',
    name: '10ml Acetic Acid 0.6%',
    slug: '10ml-acetic-acid-0-6',
    shortDescription: 'Analytical-grade 0.6% Acetic Acid solution for peptide solubility research.',
    description: '10ml Acetic Acid 0.6% solution, prepared with high-purity distilled water. Designed for laboratory use in solubilizing specific research peptides. This solution meets strict laboratory quality control standards. Strictly for research use only.',
    format: 'Liquid Solution',
    price: 6,
    image: '/products/10ml-acetic-acid-0-6.png',
    category: 'Peptides',
    batchDataAvailable: true,
    seoTitle: 'Buy 10ml Acetic Acid 0.6% UK | Peptide Research Solution',
    metaDescription: 'Analytical-grade 0.6% Acetic Acid 10ml for research peptide solubility. High-purity laboratory solution. Fast UK shipping. Research use only.'
  },
  {
    id: '14',
    name: 'ACE-031 1mg (95% Untagged Premium)',
    slug: 'ace-031-1mg-95-untagged-premium',
    shortDescription: 'Premium Untagged ACE-031 1mg for laboratory biochemical analysis.',
    description: 'ACE-031 1mg (ACVR2B-Fc) is a soluble decoy receptor for myostatin. This untagged premium version is produced via recombinant DNA technology and purified to 95%+ for high-precision scientific research into muscle regulation pathways. Research use only.',
    format: 'Lyophilized Powder',
    price: 79,
    image: '/products/ace-031-1mg-95-untagged-premium.png',
    category: 'Peptides',
    batchDataAvailable: true,
    seoTitle: 'ACE-031 1mg UK | Premium Untagged Research Peptide',
    metaDescription: 'Buy ACE-031 1mg research peptide. Premium untagged version with 95%+ purity. Recombinant DNA technology produced. Fast, secure UK shipping.'
  },
  {
    id: '15',
    name: 'ACTH 1-39 5mg',
    slug: 'acth-1-39-5mg',
    shortDescription: 'Synthetic ACTH (1-39) 5mg for endocrine research and laboratory testing.',
    description: 'Adrenocorticotropic Hormone (ACTH) 1-39 5mg is a synthetic peptide containing the full sequence of the native hormone. Verified for purity and molecular identity, this material is designed for complex endocrine research and receptor studies. Research use only.',
    format: 'Lyophilized Powder',
    price: 85,
    image: '/products/acth-1-39-5mg.png',
    category: 'Peptides',
    batchDataAvailable: true,
    seoTitle: 'ACTH 1-39 5mg UK | Buy High Purity Research ACTH',
    metaDescription: 'Premium ACTH 1-39 5mg research peptide. Synthetic full-sequence hormone for laboratory testing. 99% HPLC purity verified. Reliable UK supplier.'
  },
  {
    id: '16',
    name: 'ADAMAX 5mg',
    slug: 'adamax-5mg',
    shortDescription: 'High-purity ADAMAX 5mg research compound for biochemical analysis.',
    description: 'ADAMAX 5mg is an optimized version of the research peptide Semax. This synthetic analog is designed for stability and enhanced laboratory research. Each vial is HPLC verified for purity and chemical consistency. Strictly for research use only.',
    format: 'Lyophilized Powder',
    price: 49,
    image: '/products/adamax-5mg.png',
    category: 'Peptides',
    batchDataAvailable: true,
    seoTitle: 'ADAMAX 5mg UK | Optimized Semax Analog Research Peptide',
    metaDescription: 'Buy high-purity ADAMAX 5mg research compound. HPLC verified semax analog for laboratory studies. Secure ordering and fast UK delivery.'
  },
  {
    id: '17',
    name: 'AOD 9604 2MG',
    slug: 'aod-9604-2mg',
    shortDescription: 'Advanced Obesity Drug analog AOD-9604 2mg for lipid research.',
    description: 'AOD 9604 2mg is a synthetic fragment of the C-terminus of growth hormone (Tyr-hGH 177-191). This high-purity lyophilized peptide is used in laboratory studies investigating lipid metabolism and adipose tissue research. Research use only.',
    format: 'Lyophilized Powder',
    price: 27.95,
    image: '/products/aod-9604-2mg.png',
    category: 'Peptides',
    batchDataAvailable: true,
    seoTitle: 'AOD 9604 2mg UK | HPLC Verified Lipid Research Peptide',
    metaDescription: 'Buy AOD 9604 2mg research peptide. High-purity C-terminal GH fragment for laboratory metabolism studies. HPLC tested. Fast UK dispatch.'
  },
  {
    id: '18',
    name: 'AOD 9604 5MG',
    slug: 'aod-9604-5mg',
    shortDescription: 'High-purity AOD-9604 5mg peptide fragment for scientific research.',
    description: 'AOD 9604 5mg is a synthetic fragment (177-191) of growth hormone. Our laboratory-grade material is purified to >99% and lyophilized for chemical stability, ensuring consistency across laboratory replicates and testing phases. Research use only.',
    format: 'Lyophilized Powder',
    price: 55,
    image: '/products/aod-9604-5mg.png',
    category: 'Peptides',
    batchDataAvailable: true,
    seoTitle: 'AOD 9604 5mg UK | Buy Research Peptide Fragment',
    metaDescription: 'Premium AOD 9604 5mg. High-purity growth hormone fragment 177-191. HPLC verified for research consistency. Fast UK delivery from RetaPharma.'
  },
  {
    id: '19',
    name: 'ARA-290 16mg',
    slug: 'ara-290-16mg',
    shortDescription: 'Synthetic ARA-290 16mg peptide for erythropoietin receptor research.',
    description: 'ARA-290 16mg is a synthetic 11-amino acid peptide derived from erythropoietin. This high-purity research compound is designed for laboratory investigation of non-erythropoietic receptor interactions and tissue studies. Research use only.',
    format: 'Lyophilized Powder',
    price: 75,
    image: '/products/ara-290-16mg.png',
    category: 'Peptides',
    batchDataAvailable: true,
    seoTitle: 'ARA-290 16mg UK | Synthetic EPO-Derived Research Peptide',
    metaDescription: 'High-purity ARA-290 16mg research peptide. 11-amino acid synthetic EPO fragment. HPLC verified. Fast, tracked UK shipping for laboratory use.'
  },
  {
    id: '20',
    name: 'B7-33 2mg',
    slug: 'b7-33-2mg',
    shortDescription: 'High-purity Relaxin-3 analog B7-33 2mg for scientific research.',
    description: 'B7-33 2mg is a synthetic, single-chain analog of the H2 relaxin peptide. Produced to stringent laboratory standards, this research-grade material is verified for high purity (>99%) and molecular identity for use in structural research. Research use only.',
    format: 'Lyophilized Powder',
    price: 22.95,
    image: '/products/b7-33-2mg.png',
    category: 'Peptides',
    batchDataAvailable: true,
    seoTitle: 'B7-33 2mg UK | Synthetic Relaxin Analog Research Peptide',
    metaDescription: 'Buy B7-33 2mg research peptide. High-purity synthetic relaxin analog for laboratory investigation. HPLC verified. Reliable UK supplier.'
  },
  {
    id: '21',
    name: 'Bronchogen 20mg',
    slug: 'bronchogen-20mg',
    shortDescription: 'Research-grade Bronchogen 20mg bioregulator peptide for laboratory testing.',
    description: 'Bronchogen 20mg is a short synthetic peptide (bioregulator). Our production ensures high chemical purity and consistency for laboratory research into peptide-regulated cellular processes. Lyophilized for stability. Strictly for research use only.',
    format: 'Lyophilized Powder',
    price: 39,
    image: '/products/bronchogen-20mg.png',
    category: 'Peptides',
    batchDataAvailable: true,
    seoTitle: 'Bronchogen 20mg UK | Synthetic Bioregulator Research Peptide',
    metaDescription: 'Premium Bronchogen 20mg. Synthetic bioregulator peptide for laboratory research. High-purity lyophilized material. Fast UK dispatch.'
  },
  {
    id: '22',
    name: 'Cardiogen 20mg - Bioregulator Peptide',
    slug: 'cardiogen-20mg-bioregulator-peptide',
    shortDescription: 'High-purity Cardiogen 20mg bioregulator for scientific research studies.',
    description: 'Cardiogen 20mg is a synthetic tetrapeptide bioregulator. Purified via HPLC to >99%, this research-grade material is supplied in a stable lyophilized format for laboratory investigation of peptide-protein interactions. Research use only.',
    format: 'Lyophilized Powder',
    price: 49,
    image: '/products/cardiogen-20mg-bioregulator-peptide.png',
    category: 'Peptides',
    batchDataAvailable: true,
    seoTitle: 'Cardiogen 20mg UK | Tetrapeptide Bioregulator Research Material',
    metaDescription: 'Buy Cardiogen 20mg research peptide. High-purity synthetic bioregulator for laboratory studies. HPLC verified. Fast UK shipping from RetaPharma.'
  },
  {
    id: '23',
    name: 'Cartalax 20mg - Bioregulator',
    slug: 'cartalax-20mg-bioregulator',
    shortDescription: 'Synthetic Cartalax 20mg bioregulator peptide for laboratory analysis.',
    description: 'Cartalax 20mg is a synthetic tripeptide bioregulator. Designed for high precision in-vitro research, each vial is verified for chemical identity and high purity through 3rd party laboratory analysis. Strictly for research use only.',
    format: 'Lyophilized Powder',
    price: 49,
    image: '/products/cartalax-20mg-bioregulator.png',
    category: 'Peptides',
    batchDataAvailable: true,
    seoTitle: 'Cartalax 20mg UK | Tripeptide Bioregulator Research Peptide',
    metaDescription: 'High-purity Cartalax 20mg. Synthetic tripeptide bioregulator for scientific research. HPLC tested. Fast, secure UK shipping.'
  },
  {
    id: '24',
    name: 'CJC-1295 MOD GRF 1-29 / without DAC 5mg',
    slug: 'cjc-1295-mod-grf-1-29-without-dac-5mg',
    shortDescription: 'High-purity Modified GRF (1-29) 5mg for large-scale research studies.',
    description: 'CJC-1295 without DAC 5mg (Modified GRF 1-29) is a synthetic analog of growth hormone-releasing hormone. This larger format vial is produced for extensive laboratory testing and research protocols requiring high-purity synthetic peptides. Research use only.',
    format: 'Lyophilized Powder',
    price: 25.95,
    image: '/products/cjc-1295-mod-grf-1-29-without-dac-5mg.png',
    category: 'Peptides',
    batchDataAvailable: true,
    seoTitle: 'CJC-1295 MOD GRF 1-29 5mg UK | 99% Purity Research Peptides',
    metaDescription: 'Buy CJC-1295 (Mod GRF 1-29) 5mg. 99%+ HPLC purity. No DAC. High-quality research peptide lyophilized for stability. Fast UK shipping.'
  },
  {
    id: '25',
    name: 'CJC-1295 With DAC 2mg',
    slug: 'cjc-1295-with-dac-2mg',
    shortDescription: 'CJC-1295 with Drug Affinity Complex (DAC) 2mg for research stability studies.',
    description: 'CJC-1295 With DAC 2mg is a synthetic GHRH analog with an added Drug Affinity Complex for extended stability in laboratory research environments. Verified for high chemical purity and molecular weight consistency. Research use only.',
    format: 'Lyophilized Powder',
    price: 22,
    image: '/products/cjc-1295-with-dac-2mg.png',
    category: 'Peptides',
    batchDataAvailable: true,
    seoTitle: 'CJC-1295 With DAC 2mg UK | High Purity Research Peptides',
    metaDescription: 'Premium CJC-1295 With DAC 2mg. Laboratory-grade peptide with Drug Affinity Complex. 99% HPLC purity. Fast UK dispatch for research use.'
  },
  {
    id: '26',
    name: 'CJC-1295 With DAC 5mg',
    slug: 'cjc-1295-with-dac-5mg',
    shortDescription: '99%+ Purity CJC-1295 with DAC 5mg for advanced laboratory investigation.',
    description: 'CJC-1295 with DAC 5mg is a synthetic growth hormone-releasing hormone analog with DAC for increased half-life research. Supplied in high-purity lyophilized format, ideal for complex structural and biochemical testing protocols. Research use only.',
    format: 'Lyophilized Powder',
    price: 40,
    image: '/products/cjc-1295-with-dac-5mg.png',
    category: 'Peptides',
    batchDataAvailable: true,
    seoTitle: 'Buy CJC-1295 With DAC 5mg UK | Laboratory Grade Peptides',
    metaDescription: 'CJC-1295 with DAC 5mg research peptide. HPLC verified 99%+ purity. Lyophilized for stability. Fast, tracked UK shipping for laboratory testing.'
  },
  {
    id: '27',
    name: 'Colivelin 10mg',
    slug: 'colivelin-10mg',
    shortDescription: 'High-purity Colivelin 10mg research peptide for neuro-biochemical studies.',
    description: 'Colivelin 10mg is a potent synthetic neuroprotective peptide (Humanin analog). Our laboratory-grade Colivelin is purified to >99% and verified for high chemical stability and biological identity in research settings. Strictly for research use only.',
    format: 'Lyophilized Powder',
    price: 69.99,
    image: '/products/colivelin-10mg.png',
    category: 'Peptides',
    batchDataAvailable: true,
    seoTitle: 'Colivelin 10mg UK | Humanin Analog Research Peptide',
    metaDescription: 'Buy Colivelin 10mg research peptide. High-purity neuroprotective analog for laboratory studies. HPLC verified. Secure UK shipping.'
  },
  {
    id: '28',
    name: 'Cortagen 20mg',
    slug: 'cortagen-20mg',
    shortDescription: 'Synthetic Cortagen 20mg bioregulator for laboratory research analysis.',
    description: 'Cortagen 20mg is a short synthetic bioregulator peptide. Verified for high purity (>99%) through HPLC, this lyophilized research compound is designed for investigating peptide-regulated metabolic pathways. Research use only.',
    format: 'Lyophilized Powder',
    price: 49,
    image: '/products/cortagen-20mg.png',
    category: 'Peptides',
    batchDataAvailable: true,
    seoTitle: 'Cortagen 20mg UK | Synthetic Bioregulator Research Material',
    metaDescription: 'Premium Cortagen 20mg. Synthetic bioregulator peptide for laboratory research. 99% HPLC purity. Fast UK delivery from RetaPharma.'
  },
  {
    id: '29',
    name: 'Crystagen 20mg',
    slug: 'crystagen-20mg',
    shortDescription: 'High-purity Crystagen 20mg bioregulator peptide for scientific research.',
    description: 'Crystagen 20mg is a synthetic tripeptide bioregulator. Produced under strict quality control, each vial is verified for high chemical purity and bio-identity, ensuring reliable data for scientific investigation. Research use only.',
    format: 'Lyophilized Powder',
    price: 59,
    image: '/products/crystagen-20mg.png',
    category: 'Peptides',
    batchDataAvailable: true,
    seoTitle: 'Crystagen 20mg UK | Tripeptide Bioregulator Research Peptide',
    metaDescription: 'Buy Crystagen 20mg research peptide. Synthetic tripeptide bioregulator with 99% HPLC purity. Secure ordering and fast UK shipping.'
  },
  {
    id: '30',
    name: 'Dermorphin 2mg',
    slug: 'dermorphin-2mg',
    shortDescription: 'Synthetic Dermorphin 2mg hepta-peptide for opioid receptor research.',
    description: 'Dermorphin 2mg is a synthetic version of the naturally occurring hepta-peptide. Verified for high purity (>99%) and molecular weight consistency, this material is designed for scientific research into receptor binding and signaling. Research use only.',
    format: 'Lyophilized Powder',
    price: 29,
    image: '/products/dermorphin-2mg.png',
    category: 'Peptides',
    batchDataAvailable: true,
    seoTitle: 'Dermorphin 2mg UK | Synthetic Heptapeptide Research Material',
    metaDescription: 'High-purity Dermorphin 2mg research peptide. Synthetic hepta-peptide for receptor studies. HPLC tested. Fast, secure UK delivery.'
  },
  {
    id: '31',
    name: 'Dihexa 10mg',
    slug: 'dihexa-10mg',
    shortDescription: 'High-purity Dihexa 10mg compound for biochemical and neurological research.',
    description: 'Dihexa 10mg is a small, synthetic oligopeptide derivative. Our laboratory-grade material is purified via HPLC to exceed 99% purity, ensuring stability and consistency for varied research and analytical applications. Strictly for research use only.',
    format: 'Lyophilized Powder',
    price: 59,
    image: '/products/dihexa-10mg.png',
    category: 'Peptides',
    batchDataAvailable: true,
    seoTitle: 'Dihexa 10mg UK | High Purity Research Compound',
    metaDescription: 'Buy Dihexa 10mg research compound. 99% HPLC verified purity. Synthetic oligopeptide for laboratory studies. Fast UK dispatch.'
  },
  {
    id: '32',
    name: 'DNSP 11 5mg',
    slug: 'dnsp-11-5mg',
    shortDescription: 'High-purity DNSP-11 5mg research peptide for laboratory analysis.',
    description: 'DNSP-11 5mg is a synthetic 11-amino acid peptide derived from glial cell line-derived neurotrophic factor. Verified for high bio-identity and purity, this material is used in research investigating cellular survival pathways. Research use only.',
    format: 'Lyophilized Powder',
    price: 75,
    image: '/products/dnsp-11-5mg.png',
    category: 'Peptides',
    batchDataAvailable: true,
    seoTitle: 'DNSP-11 5mg UK | Synthetic 11-Amino Acid Research Peptide',
    metaDescription: 'Premium DNSP-11 5mg research peptide. 99% HPLC purity. Synthetic neurotrophic factor fragment for laboratory testing. Fast UK shipping.'
  },
  {
    id: '33',
    name: 'DSIP 5mg',
    slug: 'dsip-5mg',
    shortDescription: 'Deep Sleep Inducing Peptide (DSIP) 5mg for scientific research.',
    description: 'DSIP 5mg is a synthetic nonapeptide first isolated from the cerebral venous blood of rabbits. Our laboratory-grade DSIP is purified to >99% and lyophilized for chemical stability during research and testing protocols. Research use only.',
    format: 'Lyophilized Powder',
    price: 13.95,
    image: '/products/dsip-5mg.png',
    category: 'Peptides',
    batchDataAvailable: true,
    seoTitle: 'DSIP 5mg UK | Deep Sleep Inducing Peptide Research Grade',
    metaDescription: 'Buy high-purity DSIP 5mg. 99% HPLC verified nonapeptide for scientific research. Stable lyophilized material. Fast UK delivery from RetaPharma.'
  },
  {
    id: '34',
    name: 'GHK-Cu 50mg (Copper Peptide)',
    slug: 'ghk-cu-50mg-copper-peptide',
    shortDescription: 'High-purity Copper Peptide GHK-Cu 50mg for laboratory research.',
    description: 'GHK-Cu 50mg is a synthetic tripeptide with a high affinity for copper ions. Verified for chemical purity (>99%) and metal complex stability, this research-grade material is suitable for varied biochemical and tissue research applications. Research use only.',
    format: 'Lyophilized Powder',
    price: 26.99,
    image: '/products/ghk-cu-50mg-copper-peptide.png',
    category: 'Peptides',
    batchDataAvailable: true,
    seoTitle: 'GHK-Cu 50mg UK | Copper Peptide Research Grade Material',
    metaDescription: 'Buy GHK-Cu 50mg (Copper Peptide) research material. 99% HPLC purity. High-quality synthetic tripeptide for laboratory research. Fast UK shipping.'
  },
  {
    id: '35',
    name: 'PT-141 Bremelanotide 10mg',
    slug: 'pt-141-bremelanotide-10mg',
    shortDescription: 'Synthetic Bremelanotide PT-141 10mg for melanocortin receptor research.',
    description: 'PT-141 Bremelanotide 10mg is a synthetic peptide analog of alpha-MSH. This research-grade material is purified to >99% and supplied in a stable lyophilized format for investigating melanocortin system signaling. Research use only.',
    format: 'Lyophilized Powder',
    price: 21,
    image: '/products/pt-141-bremelanotide-10mg.png',
    category: 'Peptides',
    batchDataAvailable: true,
    seoTitle: 'PT-141 Bremelanotide 10mg UK | High Purity Research Peptides',
    metaDescription: 'Premium PT-141 10mg research peptide. HPLC verified 99% purity. Synthetic melanocortin agonist for laboratory studies. Fast UK dispatch.'
  },
  {
    id: '36',
    name: 'IGF1-LR3 1mg',
    slug: 'igf1-lr3-1mg',
    shortDescription: 'Long R3 IGF-1 1mg research peptide for cellular growth signaling studies.',
    description: 'IGF1-LR3 1mg is a synthetic analog of human insulin-like growth factor 1 with an extended sequence for increased stability. Our laboratory-grade material is verified for high purity and molecular identity. Strictly for research use only.',
    format: 'Lyophilized Powder',
    price: 59,
    image: '/products/igf1-lr3-1mg.png',
    category: 'Peptides',
    batchDataAvailable: true,
    seoTitle: 'IGF1-LR3 1mg UK | Long R3 Insulin-Like Growth Factor Research',
    metaDescription: 'High-purity IGF1-LR3 1mg research peptide. Extended stability analog for laboratory signaling studies. HPLC tested. Fast, secure UK shipping.'
  },
  {
    id: '37',
    name: 'Tesamorelin 2mg',
    slug: 'tesamorelin-2mg',
    shortDescription: 'High-purity Tesamorelin 2mg GHRH analog for biochemical research.',
    description: 'Tesamorelin 2mg is a synthetic analog of growth hormone-releasing factor. Purified to >99% via HPLC, this research-grade material is supplied as a stable lyophilized cake for use in varied scientific testing environments. Research use only.',
    format: 'Lyophilized Powder',
    price: 29,
    image: '/products/tesamorelin-2mg.png',
    category: 'Peptides',
    batchDataAvailable: true,
    seoTitle: 'Tesamorelin 2mg UK | High Purity GHRH Analog Research Peptide',
    metaDescription: 'Buy Tesamorelin 2mg research peptide. 99% HPLC verified purity. Synthetic growth hormone-releasing factor analog. Fast UK delivery.'
  }
,
  {
    id: '38',
    name: 'Alluvi Glow GHK-Cu – BPC-157 & TB-500 70mg',
    slug: 'alluvi-glow-ghk-cu-bpc-157-tb-500-70mg',
    shortDescription: 'Advanced research peptide blend (GHK-Cu, BPC-157, TB-500) in a 70mg pen format.',
    description: 'Alluvi Glow is a specialized research blend containing GHK-Cu, BPC-157, and TB-500. This 70mg multi-peptide formulation is designed for laboratory investigation of synergistic peptide interactions in scientific research settings. Research use only.',
    format: 'Peptide Pen',
    price: 89.99,
    image: '/products/alluvi-glow-ghk-cu-bpc-157-tb-500-70mg.png',
    category: 'Alluvi',
    batchDataAvailable: true,
    seoTitle: 'Alluvi Glow 70mg Pen UK | GHK-Cu, BPC-157, TB-500 Research Blend',
    metaDescription: 'Premium Alluvi Glow research peptide pen. 70mg blend of GHK-Cu, BPC-157, and TB-500. HPLC verified purity. Fast UK delivery for lab use.'
  },
  {
    id: '39',
    name: 'Alluvi NAD+ 1000mg',
    slug: 'alluvi-nad-1000mg',
    shortDescription: 'High-purity NAD+ (Nicotinamide Adenine Dinucleotide) 1000mg research pen.',
    description: 'Alluvi NAD+ provides 1000mg of high-purity Nicotinamide Adenine Dinucleotide in a specialized research pen. Verified for concentration and chemical identity, this material is designed for laboratory research into cellular energy and aging pathways. Research use only.',
    format: 'Peptide Pen',
    price: 169.99,
    image: '/products/alluvi-nad-1000mg.png',
    category: 'Alluvi',
    batchDataAvailable: true,
    seoTitle: 'Alluvi NAD+ 1000mg Pen UK | High Purity Research Material',
    metaDescription: 'Buy Alluvi NAD+ 1000mg research pen. High-purity Nicotinamide Adenine Dinucleotide for laboratory studies. Secure ordering and fast UK shipping.'
  },
  {
    id: '40',
    name: 'Alluvi Retatrutide 20mg (R&D)',
    slug: 'alluvi-retatrutide-20mg-r-d',
    shortDescription: 'Research & Development grade Retatrutide 20mg triple agonist pen.',
    description: 'Alluvi Retatrutide 20mg (R&D Grade) is a synthetic triple receptor agonist (GIP, GLP-1, Glucagon). Sourced for precision biochemical research and analytical testing, each pen is verified for concentration and molecular identity. Strictly for research use only.',
    format: 'Peptide Pen',
    price: 100,
    image: '/products/alluvi-retatrutide-20mg-r-d.png',
    category: 'Alluvi',
    batchDataAvailable: true,
    seoTitle: 'Alluvi Retatrutide 20mg UK | R&D Grade Research Peptide Pen',
    metaDescription: 'Premium Alluvi Retatrutide 20mg R&D pen. High-purity triple hormone receptor agonist for laboratory research. Fast, tracked UK delivery.'
  },
  {
    id: '41',
    name: 'Alluvi Retatrutide 20mg ×2 Bundle',
    slug: 'alluvi-retatrutide-20mg-2-bundle',
    shortDescription: 'Double bundle of Alluvi Retatrutide 20mg pens for extensive research studies.',
    description: 'This research bundle contains two Alluvi Retatrutide 20mg pens, providing a total of 40mg of high-purity triple hormone receptor agonist. Designed for laboratories conducting multi-phase testing or comparative research protocols. Research use only.',
    format: 'Peptide Pen',
    price: 199.99,
    image: '/products/alluvi-retatrutide-20mg-2-bundle.png',
    category: 'Alluvi',
    batchDataAvailable: true,
    seoTitle: 'Alluvi Retatrutide 20mg Bundle UK | Research Peptide Pens',
    metaDescription: 'Buy Alluvi Retatrutide 20mg double bundle. High-purity triple agonist for scientific research. HPLC verified concentration. Fast UK shipping.'
  },
  {
    id: '42',
    name: 'Alluvi Retatrutide 40mg',
    slug: 'alluvi-retatrutide-40mg',
    shortDescription: 'High-concentration Alluvi Retatrutide 40mg triple agonist research pen.',
    description: 'Alluvi Retatrutide 40mg is a high-purity synthetic triple receptor agonist (GIP, GLP-1, and Glucagon). This high-concentration pen is produced to stringent laboratory standards for use in advanced scientific and analytical research. Research use only.',
    format: 'Peptide Pen',
    price: 189.99,
    image: '/products/alluvi-retatrutide-40mg.png',
    category: 'Alluvi',
    batchDataAvailable: true,
    seoTitle: 'Alluvi Retatrutide 40mg Pen UK | High Purity Research Peptides',
    metaDescription: 'Premium Alluvi Retatrutide 40mg research pen. 99% verified purity triple receptor agonist. Fast UK delivery from RetaPharma UK.'
  },
  {
    id: '43',
    name: 'Alluvi Retatrutide 40mg ×2 Bundle',
    slug: 'alluvi-retatrutide-40mg-2-bundle',
    shortDescription: 'Double bundle of high-concentration Alluvi Retatrutide 40mg research pens.',
    description: 'This laboratory bundle includes two Alluvi Retatrutide 40mg pens, offering 80mg total of high-purity triple hormone receptor agonist. Ideal for high-throughput laboratory research and comprehensive analytical testing. Research use only.',
    format: 'Peptide Pen',
    price: 315,
    image: '/products/alluvi-retatrutide-40mg-2-bundle.png',
    category: 'Alluvi',
    batchDataAvailable: true,
    seoTitle: 'Alluvi Retatrutide 40mg Bundle UK | Laboratory Research Pens',
    metaDescription: 'Buy Alluvi Retatrutide 40mg double bundle. High-concentration research pens with HPLC verified purity. Secure ordering and fast UK delivery.'
  },
  {
    id: '44',
    name: 'Alluvi Retatrutide BPC-157 & TB-500 40mg',
    slug: 'alluvi-retatrutide-bpc-157-tb-500-40mg',
    shortDescription: 'Complex research blend: Retatrutide, BPC-157, and TB-500 in a 40mg pen.',
    description: 'Alluvi Retatrutide + BPC-157 + TB-500 is a specialized 40mg research blend. This formulation is designed for scientific investigation into the combined effects of triple receptor agonists and regenerative peptide analogs in laboratory research. Research use only.',
    format: 'Peptide Pen',
    price: 139.99,
    image: '/products/alluvi-retatrutide-bpc-157-tb-500-40mg.png',
    category: 'Alluvi',
    batchDataAvailable: true,
    seoTitle: 'Alluvi Retatrutide + BPC + TB 40mg Pen UK | Research Peptide Blend',
    metaDescription: 'Premium Alluvi research pen containing Retatrutide, BPC-157, and TB-500. 40mg high-purity blend for laboratory testing. Fast UK shipping.'
  },
  {
    id: '45',
    name: 'Alluvi Tirzepatide 20mg',
    slug: 'alluvi-tirzepatide-20mg',
    shortDescription: 'High-purity Alluvi Tirzepatide 20mg dual GIP/GLP-1 receptor agonist pen.',
    description: 'Alluvi Tirzepatide 20mg is a synthetic dual receptor agonist of GIP and GLP-1. Sourced for high-precision scientific research, each pen is verified for concentration and chemical identity through rigorous 3rd party laboratory testing. Research use only.',
    format: 'Peptide Pen',
    price: 79.99,
    image: '/products/alluvi-tirzepatide-20mg.png',
    category: 'Alluvi',
    batchDataAvailable: true,
    seoTitle: 'Alluvi Tirzepatide 20mg Pen UK | Dual Receptor Agonist Research',
    metaDescription: 'Buy Alluvi Tirzepatide 20mg research pen. High-purity dual GIP/GLP-1 agonist for laboratory studies. HPLC verified. Fast UK delivery.'
  },
  {
    id: '46',
    name: 'Alluvi Tirzepatide 40mg',
    slug: 'alluvi-tirzepatide-40mg',
    shortDescription: 'Advanced Alluvi Tirzepatide 40mg dual agonist research pen.',
    description: 'Alluvi Tirzepatide 40mg offers a high concentration of high-purity dual GIP/GLP-1 receptor agonist. This research-grade pen is produced to professional laboratory standards, ensuring consistency and stability for advanced scientific research. Research use only.',
    format: 'Peptide Pen',
    price: 119.99,
    image: '/products/alluvi-tirzepatide-40mg.png',
    category: 'Alluvi',
    batchDataAvailable: true,
    seoTitle: 'Alluvi Tirzepatide 40mg Pen UK | High Purity Research Material',
    metaDescription: 'Premium Alluvi Tirzepatide 40mg research pen. 99% HPLC purity verified dual agonist. Secure ordering and fast UK delivery for lab research.'
  },
  {
    id: '47',
    name: 'Retava GHK-Cu 50mg',
    slug: 'retava-ghk-cu-50mg',
    shortDescription: 'Premium Retava GHK-Cu 50mg copper peptide research pen.',
    description: 'Retava GHK-Cu 50mg provides a high concentration of synthetic copper peptide (GHK-Cu) in a specialized research pen format. Verified for chemical stability and high purity (>99%) for use in various laboratory research applications. Research use only.',
    format: 'Peptide Pen',
    price: 100,
    image: '/products/retava-ghk-cu-50mg.png',
    category: 'Reteva',
    batchDataAvailable: true,
    seoTitle: 'Retava GHK-Cu 50mg Pen UK | High Purity Copper Peptide Research',
    metaDescription: 'Buy Retava GHK-Cu 50mg research pen. High-purity copper peptide for laboratory testing. HPLC verified. Fast, tracked UK shipping.'
  },
  {
    id: '48',
    name: 'Retava Retatrutide 10mg',
    slug: 'retava-retatrutide-10mg',
    shortDescription: 'High-purity Retava Retatrutide 10mg triple hormone receptor agonist pen.',
    description: 'Retava Retatrutide 10mg is a premium synthetic triple agonist of GLP-1, GIP, and Glucagon receptors. Sourced for research-grade precision, each pen is verified for high concentration and molecular bio-identity. Strictly for research use only.',
    format: 'Peptide Pen',
    price: 150,
    image: '/products/retava-retatrutide-10mg.png',
    category: 'Reteva',
    batchDataAvailable: true,
    seoTitle: 'Retava Retatrutide 10mg Pen UK | Triple Agonist Research Peptide',
    metaDescription: 'Premium Retava Retatrutide 10mg research pen. High-purity triple hormone receptor agonist. HPLC verified. Fast UK delivery from RetaPharma.'
  },
  {
    id: '49',
    name: 'Retava Retatrutide 30mg',
    slug: 'retava-retatrutide-30mg',
    shortDescription: 'Advanced Retava Retatrutide 30mg triple receptor agonist research pen.',
    description: 'Retava Retatrutide 30mg offers a high concentration of high-purity synthetic triple agonist material. Verified for purity and molecular identity, this research pen is designed for complex laboratory investigation and analytical testing. Research use only.',
    format: 'Peptide Pen',
    price: 320,
    image: '/products/retava-retatrutide-30mg.png',
    category: 'Reteva',
    batchDataAvailable: true,
    seoTitle: 'Retava Retatrutide 30mg Pen UK | High Purity Research Material',
    metaDescription: 'Buy Retava Retatrutide 30mg research pen. High-purity triple receptor agonist for laboratory studies. Secure ordering and fast UK shipping.'
  },
  {
    id: '50',
    name: 'Retava Tirzepatide 10mg',
    slug: 'retava-tirzepatide-10mg',
    shortDescription: 'High-purity Retava Tirzepatide 10mg dual receptor agonist research pen.',
    description: 'Retava Tirzepatide 10mg is a synthetic dual GIP/GLP-1 receptor agonist. Sourced for high precision in scientific research, each pen is verified for concentration and bio-identity through 3rd party laboratory analysis. Research use only.',
    format: 'Peptide Pen',
    price: 120,
    image: '/products/retava-tirzepatide-10mg.png',
    category: 'Reteva',
    batchDataAvailable: true,
    seoTitle: 'Retava Tirzepatide 10mg Pen UK | Dual Agonist Research Peptide',
    metaDescription: 'Premium Retava Tirzepatide 10mg research pen. High-purity dual GIP/GLP-1 agonist for laboratory research. HPLC tested. Fast UK delivery.'
  },
  {
    id: '51',
    name: 'Retava Tirzepatide 30mg',
    slug: 'retava-tirzepatide-30mg',
    shortDescription: 'Advanced Retava Tirzepatide 30mg dual GIP/GLP-1 receptor agonist pen.',
    description: 'Retava Tirzepatide 30mg provides a high concentration of high-purity dual agonist material. This research-grade pen is produced to stringent standards, ensuring stability and consistency for laboratory research applications. Research use only.',
    format: 'Peptide Pen',
    price: 290,
    image: '/products/retava-tirzepatide-30mg.png',
    category: 'Reteva',
    batchDataAvailable: true,
    seoTitle: 'Retava Tirzepatide 30mg Pen UK | High Purity Research Material',
    metaDescription: 'Buy Retava Tirzepatide 30mg research pen. High-purity dual receptor agonist for laboratory studies. Secure ordering and fast UK shipping.'
  },
  {
    id: '52',
    name: 'Melanotan II (MT2) 10mg',
    slug: 'melanotan-ii-mt2-10mg',
    shortDescription: 'High-purity synthetic cyclic heptapeptide analog for scientific research.',
    description: 'Melanotan II (MT2) 10mg is supplied as high-purity lyophilized powder (>99%). This synthetic cyclic heptapeptide analog of alpha-melanocyte stimulating hormone is designed for laboratory research and analytical testing. Research use only.',
    format: 'Lyophilized Powder',
    price: 22.95,
    image: '/products/melanotan-ii-mt2-10mg.png',
    category: 'Peptides',
    batchDataAvailable: true,
    seoTitle: 'Melanotan II (MT2) 10mg UK | Buy High Purity Research Peptides',
    metaDescription: 'Premium Melanotan II (MT2) 10mg research peptide. 99% HPLC verified purity. Lyophilized for stability. Fast UK shipping from RetaPharma.'
  },
  {
    id: '53',
    name: 'Retatrutide 5mg',
    slug: 'retatrutide-5mg',
    shortDescription: 'High-purity Retatrutide 5mg triple receptor agonist research compound.',
    description: 'Retatrutide 5mg is a synthetic triple receptor agonist (GIP, GLP-1, Glucagon). Sourced for laboratory research and biochemical testing, this high-purity lyophilized powder is verified via HPLC for concentration and identity. Research use only.',
    format: 'Lyophilized Powder',
    price: 49.99,
    image: '/products/retatrutide-5mg.png',
    category: 'Peptides',
    batchDataAvailable: true,
    seoTitle: 'Retatrutide 5mg Peptide UK | Triple Agonist Research Grade',
    metaDescription: 'Buy Retatrutide 5mg research peptide. High-purity triple hormone receptor agonist for laboratory studies. HPLC verified. Fast UK shipping.'
  },
  {
    id: '54',
    name: 'Retatrutide 10mg',
    slug: 'retatrutide-10mg',
    shortDescription: '99%+ Purity Retatrutide 10mg triple agonist for laboratory research.',
    description: 'Retatrutide 10mg is a synthetic triple receptor agonist of GIP, GLP-1, and Glucagon receptors. Our laboratory-grade material is purified via HPLC to exceed 99% purity and lyophilized for maximum stability during research. Research use only.',
    format: 'Lyophilized Powder',
    price: 89.99,
    image: '/products/retatrutide-10mg.png',
    category: 'Peptides',
    batchDataAvailable: true,
    seoTitle: 'Retatrutide 10mg UK | HPLC Verified Triple Agonist Research',
    metaDescription: 'Premium Retatrutide 10mg research peptide. 99% HPLC verified purity. Triple hormone receptor agonist for scientific studies. Fast UK delivery.'
  },
  {
    id: '55',
    name: 'Retatrutide 20mg',
    slug: 'retatrutide-20mg',
    shortDescription: 'Advanced Retatrutide 20mg triple receptor agonist for scientific studies.',
    description: 'Retatrutide 20mg is a high-purity synthetic triple receptor agonist (GIP, GLP-1, Glucagon). Supplied in a stable lyophilized format, each vial is verified for molecular weight consistency and chemical purity through HPLC analysis. Research use only.',
    format: 'Lyophilized Powder',
    price: 159.99,
    image: '/products/retatrutide-20mg.png',
    category: 'Peptides',
    batchDataAvailable: true,
    seoTitle: 'Buy Retatrutide 20mg UK | High Purity Research Material',
    metaDescription: 'High-purity Retatrutide 20mg research peptide. HPLC verified 99%+ purity. Triple receptor agonist for laboratory research. Secure UK shipping.'
  },
  {
    id: '56',
    name: 'Melanotan MT-2 10mg',
    slug: 'melanotan-mt2-10mg',
    shortDescription: 'Lyophilised research peptide vial for laboratory and analytical research settings.',
    description: 'Melanotan MT-2 10mg is supplied as a sterile lyophilised research peptide vial for laboratory, analytical, and scientific research use. Verified for high chemical purity (>99%) and molecular identity for structural research studies. Research use only.',
    format: 'Lyophilized Powder',
    price: 45,
    image: '/products/melanotan-mt2-10mg.png',
    category: 'MT2',
    batchDataAvailable: true,
    seoTitle: 'Melanotan MT-2 10mg UK | HPLC Verified Research Peptides',
    metaDescription: 'Buy Melanotan MT-2 10mg research peptide. 99% HPLC verified purity. High-quality lyophilized material for laboratory testing. Fast UK dispatch.'
  }
];

export const featuredSlugs = [
  'retatrutide-10mg',
  'alluvi-retatrutide-20mg-r-d',
  'retava-retatrutide-10mg',
  'alluvi-tirzepatide-20mg',
  'retava-tirzepatide-10mg',
  'bpc-157-5mg',
  'thymosin-beta-4-5mg-tb500',
  'alluvi-glow-ghk-cu-bpc-157-tb-500-70mg',
  'retava-retatrutide-30mg',
  'alluvi-retatrutide-40mg',
  'retava-tirzepatide-30mg',
  'melanotan-ii-mt2-10mg',
  'ghk-cu-50mg-copper-peptide',
  'alluvi-retatrutide-bpc-157-tb-500-40mg',
  'retava-ghk-cu-50mg',
];

export const getFeaturedProducts = (count = 15): Product[] => {
  const featuredList: Product[] = [];
  for (const slug of featuredSlugs) {
    const p = products.find(prod => prod.slug === slug);
    if (p && !featuredList.some(item => item.id === p.id)) {
      featuredList.push(p);
    }
  }
  // Fill remaining if count exceeds specific list
  for (const p of products) {
    if (featuredList.length >= count) break;
    if (!featuredList.some(item => item.id === p.id)) {
      featuredList.push(p);
    }
  }
  return featuredList.slice(0, count);
};

export interface Article {
  id: string;
  title: string;
  slug: string;
  excerpt: string;
  date: string;
  author: string;
  category: string;
  image: string;
}

export const articles: Article[] = [
  {
    id: '1',
    title: 'Understanding Retatrutide: The Science of Triple Receptor Agonism',
    slug: 'understanding-retatrutide-science',
    excerpt: 'An in-depth look at how investigational compound retatrutide interacts with GLP-1, GIP, and Glucagon receptors in laboratory settings.',
    date: '2023-11-15',
    author: 'Dr. A. Scientist',
    category: 'Retatrutide',
    image: 'https://picsum.photos/seed/blog1/800/400',
  },
  {
    id: '2',
    title: 'How to Read a Certificate of Analysis (COA)',
    slug: 'how-to-read-coa',
    excerpt: 'A comprehensive guide to understanding HPLC purity reports, mass spectrometry data, and what they mean for peptide quality.',
    date: '2023-10-22',
    author: 'Analytical Team',
    category: 'Laboratory Testing',
    image: 'https://picsum.photos/seed/blog2/800/400',
  },
  {
    id: '3',
    title: 'Peptide Storage Principles: Maintaining Stability',
    slug: 'peptide-storage-principles',
    excerpt: 'Essential guidelines for storing lyophilized and reconstituted peptides to prevent degradation during research.',
    date: '2023-09-05',
    author: 'Lab Services',
    category: 'Peptide Education',
    image: 'https://picsum.photos/seed/blog3/800/400',
  }
];
