export interface Product {
  id: string;
  name: string;
  slug: string;
  shortDescription: string;
  description: string;
  format: string;
  price: number;
  image: string;
  category: string;
  batchDataAvailable: boolean;
}

export const products: Product[] = [
  {
    id: '5',
    name: '10ml Bacteriostatic Mixing Water',
    slug: '10ml-bacteriostatic-mixing-water',
    shortDescription: 'High-purity lyophilized peptide for scientific research.',
    description: '10ml Bacteriostatic Mixing Water is provided for research and human consumption, or therapeutic use.',
    format: 'Lyophilized Powder',
    price: 5.95,
    image: '/products/10ml-bacteriostatic-mixing-water.png',
    category: 'Peptides',
    batchDataAvailable: true,
  },
  {
    id: '6',
    name: 'BPC-157 5mg',
    slug: 'bpc-157-5mg',
    shortDescription: 'High-purity lyophilized peptide for scientific research.',
    description: 'BPC-157 5mg is provided for research and human consumption, or therapeutic use.',
    format: 'Lyophilized Powder',
    price: 16.95,
    image: '/products/bpc-157-5mg.png',
    category: 'Peptides',
    batchDataAvailable: true,
  },
  {
    id: '7',
    name: 'Thymosin Beta 4 5mg TB500',
    slug: 'thymosin-beta-4-5mg-tb500',
    shortDescription: 'High-purity lyophilized peptide for scientific research.',
    description: 'Thymosin Beta 4 5mg TB500 is provided for research and human consumption, or therapeutic use.',
    format: 'Lyophilized Powder',
    price: 33,
    image: '/products/thymosin-beta-4-5mg-tb500.png',
    category: 'Peptides',
    batchDataAvailable: true,
  },
  {
    id: '8',
    name: 'CJC-1295 MOD GRF 1-29 / without DAC 2mg',
    slug: 'cjc-1295-mod-grf-1-29-without-dac-2mg',
    shortDescription: 'High-purity lyophilized peptide for scientific research.',
    description: 'CJC-1295 MOD GRF 1-29 / without DAC 2mg is provided for research and human consumption, or therapeutic use.',
    format: 'Lyophilized Powder',
    price: 12.95,
    image: '/products/cjc-1295-mod-grf-1-29-without-dac-2mg.png',
    category: 'Peptides',
    batchDataAvailable: true,
  },
  {
    id: '9',
    name: 'Ipamorelin 2mg',
    slug: 'ipamorelin-2mg',
    shortDescription: 'High-purity lyophilized peptide for scientific research.',
    description: 'Ipamorelin 2mg is provided for research and human consumption, or therapeutic use.',
    format: 'Lyophilized Powder',
    price: 9.95,
    image: '/products/ipamorelin-2mg.png',
    category: 'Peptides',
    batchDataAvailable: true,
  },
  {
    id: '10',
    name: 'Thymosin Beta 4 2mg (TB500)',
    slug: 'thymosin-beta-4-2mg-tb500',
    shortDescription: 'High-purity lyophilized peptide for scientific research.',
    description: 'Thymosin Beta 4 2mg (TB500) is provided for research and human consumption, or therapeutic use.',
    format: 'Lyophilized Powder',
    price: 16.95,
    image: '/products/thymosin-beta-4-2mg-tb500.png',
    category: 'Peptides',
    batchDataAvailable: true,
  },
  {
    id: '11',
    name: 'GHRP-6 5mg',
    slug: 'ghrp-6-5mg',
    shortDescription: 'High-purity lyophilized peptide for scientific research.',
    description: 'GHRP-6 5mg is provided for research and human consumption, or therapeutic use.',
    format: 'Lyophilized Powder',
    price: 9.95,
    image: '/products/ghrp-6-5mg.png',
    category: 'Peptides',
    batchDataAvailable: true,
  },
  {
    id: '12',
    name: 'GHRP-2 5mg',
    slug: 'ghrp-2-5mg',
    shortDescription: 'High-purity lyophilized peptide for scientific research.',
    description: 'GHRP-2 5mg is provided for research and human consumption, or therapeutic use.',
    format: 'Lyophilized Powder',
    price: 9.95,
    image: '/products/ghrp-2-5mg.png',
    category: 'Peptides',
    batchDataAvailable: true,
  },
  {
    id: '13',
    name: '10ml Acetic Acid 0.6%',
    slug: '10ml-acetic-acid-0-6',
    shortDescription: 'High-purity lyophilized peptide for scientific research.',
    description: '10ml Acetic Acid 0.6% is provided for research and human consumption, or therapeutic use.',
    format: 'Lyophilized Powder',
    price: 6,
    image: '/products/10ml-acetic-acid-0-6.png',
    category: 'Peptides',
    batchDataAvailable: true,
  },
  {
    id: '14',
    name: 'ACE-031 1mg (95% Untagged Premium)',
    slug: 'ace-031-1mg-95-untagged-premium',
    shortDescription: 'High-purity lyophilized peptide for scientific research.',
    description: 'ACE-031 1mg (95% Untagged Premium) is provided for research and human consumption, or therapeutic use.',
    format: 'Lyophilized Powder',
    price: 79,
    image: '/products/ace-031-1mg-95-untagged-premium.png',
    category: 'Peptides',
    batchDataAvailable: true,
  },
  {
    id: '15',
    name: 'ACTH 1-39 5mg',
    slug: 'acth-1-39-5mg',
    shortDescription: 'High-purity lyophilized peptide for scientific research.',
    description: 'ACTH 1-39 5mg is provided for research and human consumption, or therapeutic use.',
    format: 'Lyophilized Powder',
    price: 85,
    image: '/products/acth-1-39-5mg.png',
    category: 'Peptides',
    batchDataAvailable: true,
  },
  {
    id: '16',
    name: 'ADAMAX 5mg',
    slug: 'adamax-5mg',
    shortDescription: 'High-purity lyophilized peptide for scientific research.',
    description: 'ADAMAX 5mg is provided for research and human consumption, or therapeutic use.',
    format: 'Lyophilized Powder',
    price: 49,
    image: '/products/adamax-5mg.jpg',
    category: 'Peptides',
    batchDataAvailable: true,
  },
  {
    id: '17',
    name: 'AOD 9604 2MG',
    slug: 'aod-9604-2mg',
    shortDescription: 'High-purity lyophilized peptide for scientific research.',
    description: 'AOD 9604 2MG is provided for research and human consumption, or therapeutic use.',
    format: 'Lyophilized Powder',
    price: 27.95,
    image: '/products/aod-9604-2mg.png',
    category: 'Peptides',
    batchDataAvailable: true,
  },
  {
    id: '18',
    name: 'AOD 9604 5MG',
    slug: 'aod-9604-5mg',
    shortDescription: 'High-purity lyophilized peptide for scientific research.',
    description: 'AOD 9604 5MG is provided for research and human consumption, or therapeutic use.',
    format: 'Lyophilized Powder',
    price: 55,
    image: '/products/aod-9604-5mg.png',
    category: 'Peptides',
    batchDataAvailable: true,
  },
  {
    id: '19',
    name: 'ARA-290 16mg',
    slug: 'ara-290-16mg',
    shortDescription: 'High-purity lyophilized peptide for scientific research.',
    description: 'ARA-290 16mg is provided for research and human consumption, or therapeutic use.',
    format: 'Lyophilized Powder',
    price: 75,
    image: '/products/ara-290-16mg.jpg',
    category: 'Peptides',
    batchDataAvailable: true,
  },
  {
    id: '20',
    name: 'B7-33 2mg',
    slug: 'b7-33-2mg',
    shortDescription: 'High-purity lyophilized peptide for scientific research.',
    description: 'B7-33 2mg is provided for research and human consumption, or therapeutic use.',
    format: 'Lyophilized Powder',
    price: 22.95,
    image: '/products/b7-33-2mg.jpg',
    category: 'Peptides',
    batchDataAvailable: true,
  },
  {
    id: '21',
    name: 'Bronchogen 20mg',
    slug: 'bronchogen-20mg',
    shortDescription: 'High-purity lyophilized peptide for scientific research.',
    description: 'Bronchogen 20mg is provided for research and human consumption, or therapeutic use.',
    format: 'Lyophilized Powder',
    price: 39,
    image: '/products/bronchogen-20mg.png',
    category: 'Peptides',
    batchDataAvailable: true,
  },
  {
    id: '22',
    name: 'Cardiogen 20mg - Bioregulator Peptide',
    slug: 'cardiogen-20mg-bioregulator-peptide',
    shortDescription: 'High-purity lyophilized peptide for scientific research.',
    description: 'Cardiogen 20mg - Bioregulator Peptide is provided for research and human consumption, or therapeutic use.',
    format: 'Lyophilized Powder',
    price: 49,
    image: '/products/cardiogen-20mg-bioregulator-peptide.jpg',
    category: 'Peptides',
    batchDataAvailable: true,
  },
  {
    id: '23',
    name: 'Cartalax 20mg - Bioregulator',
    slug: 'cartalax-20mg-bioregulator',
    shortDescription: 'High-purity lyophilized peptide for scientific research.',
    description: 'Cartalax 20mg - Bioregulator is provided for research and human consumption, or therapeutic use.',
    format: 'Lyophilized Powder',
    price: 49,
    image: '/products/cartalax-20mg-bioregulator.png',
    category: 'Peptides',
    batchDataAvailable: true,
  },
  {
    id: '24',
    name: 'CJC-1295 MOD GRF 1-29 / without DAC 5mg',
    slug: 'cjc-1295-mod-grf-1-29-without-dac-5mg',
    shortDescription: 'High-purity lyophilized peptide for scientific research.',
    description: 'CJC-1295 MOD GRF 1-29 / without DAC 5mg is provided for research and human consumption, or therapeutic use.',
    format: 'Lyophilized Powder',
    price: 25.95,
    image: '/products/cjc-1295-mod-grf-1-29-without-dac-5mg.jpg',
    category: 'Peptides',
    batchDataAvailable: true,
  },
  {
    id: '25',
    name: 'CJC-1295 With DAC 2mg',
    slug: 'cjc-1295-with-dac-2mg',
    shortDescription: 'High-purity lyophilized peptide for scientific research.',
    description: 'CJC-1295 With DAC 2mg is provided for research and human consumption, or therapeutic use.',
    format: 'Lyophilized Powder',
    price: 22,
    image: '/products/cjc-1295-with-dac-2mg.png',
    category: 'Peptides',
    batchDataAvailable: true,
  },
  {
    id: '26',
    name: 'CJC-1295 With DAC 5mg',
    slug: 'cjc-1295-with-dac-5mg',
    shortDescription: 'High-purity lyophilized peptide for scientific research.',
    description: 'CJC-1295 With DAC 5mg is provided for research and human consumption, or therapeutic use.',
    format: 'Lyophilized Powder',
    price: 40,
    image: '/products/cjc-1295-with-dac-5mg.png',
    category: 'Peptides',
    batchDataAvailable: true,
  },
  {
    id: '27',
    name: 'Colivelin 10mg',
    slug: 'colivelin-10mg',
    shortDescription: 'High-purity lyophilized peptide for scientific research.',
    description: 'Colivelin 10mg is provided for research and human consumption, or therapeutic use.',
    format: 'Lyophilized Powder',
    price: 69.99,
    image: '/products/colivelin-10mg.jpg',
    category: 'Peptides',
    batchDataAvailable: true,
  },
  {
    id: '28',
    name: 'Cortagen 20mg',
    slug: 'cortagen-20mg',
    shortDescription: 'High-purity lyophilized peptide for scientific research.',
    description: 'Cortagen 20mg is provided for research and human consumption, or therapeutic use.',
    format: 'Lyophilized Powder',
    price: 49,
    image: '/products/cortagen-20mg.jpg',
    category: 'Peptides',
    batchDataAvailable: true,
  },
  {
    id: '29',
    name: 'Crystagen 20mg',
    slug: 'crystagen-20mg',
    shortDescription: 'High-purity lyophilized peptide for scientific research.',
    description: 'Crystagen 20mg is provided for research and human consumption, or therapeutic use.',
    format: 'Lyophilized Powder',
    price: 59,
    image: '/products/crystagen-20mg.jpg',
    category: 'Peptides',
    batchDataAvailable: true,
  },
  {
    id: '30',
    name: 'Dermorphin 2mg',
    slug: 'dermorphin-2mg',
    shortDescription: 'High-purity lyophilized peptide for scientific research.',
    description: 'Dermorphin 2mg is provided for research and human consumption, or therapeutic use.',
    format: 'Lyophilized Powder',
    price: 29,
    image: '/products/dermorphin-2mg.png',
    category: 'Peptides',
    batchDataAvailable: true,
  },
  {
    id: '31',
    name: 'Dihexa 10mg',
    slug: 'dihexa-10mg',
    shortDescription: 'High-purity lyophilized peptide for scientific research.',
    description: 'Dihexa 10mg is provided for research and human consumption, or therapeutic use.',
    format: 'Lyophilized Powder',
    price: 59,
    image: '/products/dihexa-10mg.png',
    category: 'Peptides',
    batchDataAvailable: true,
  },
  {
    id: '32',
    name: 'DNSP 11 5mg',
    slug: 'dnsp-11-5mg',
    shortDescription: 'High-purity lyophilized peptide for scientific research.',
    description: 'DNSP 11 5mg is provided for research and human consumption, or therapeutic use.',
    format: 'Lyophilized Powder',
    price: 75,
    image: '/products/dnsp-11-5mg.jpg',
    category: 'Peptides',
    batchDataAvailable: true,
  },
  {
    id: '33',
    name: 'DSIP 5mg',
    slug: 'dsip-5mg',
    shortDescription: 'High-purity lyophilized peptide for scientific research.',
    description: 'DSIP 5mg is provided for research and human consumption, or therapeutic use.',
    format: 'Lyophilized Powder',
    price: 13.95,
    image: '/products/dsip-5mg.png',
    category: 'Peptides',
    batchDataAvailable: true,
  },
  {
    id: '34',
    name: 'GHK-Cu 50mg (Copper Peptide)',
    slug: 'ghk-cu-50mg-copper-peptide',
    shortDescription: 'High-purity lyophilized peptide for scientific research.',
    description: 'GHK-Cu 50mg (Copper Peptide) is provided for research and human consumption, or therapeutic use.',
    format: 'Lyophilized Powder',
    price: 26.99,
    image: '/products/ghk-cu-50mg-copper-peptide.jpg',
    category: 'Peptides',
    batchDataAvailable: true,
  },
  {
    id: '35',
    name: 'PT-141 Bremelanotide 10mg',
    slug: 'pt-141-bremelanotide-10mg',
    shortDescription: 'High-purity lyophilized peptide for scientific research.',
    description: 'PT-141 Bremelanotide 10mg is provided for research and human consumption, or therapeutic use.',
    format: 'Lyophilized Powder',
    price: 21,
    image: '/products/pt-141-bremelanotide-10mg.png',
    category: 'Peptides',
    batchDataAvailable: true,
  },
  {
    id: '36',
    name: 'IGF1-LR3 1mg',
    slug: 'igf1-lr3-1mg',
    shortDescription: 'High-purity lyophilized peptide for scientific research.',
    description: 'IGF1-LR3 1mg is provided for research and human consumption, or therapeutic use.',
    format: 'Lyophilized Powder',
    price: 59,
    image: '/products/igf1-lr3-1mg.png',
    category: 'Peptides',
    batchDataAvailable: true,
  },
  {
    id: '37',
    name: 'Tesamorelin 2mg',
    slug: 'tesamorelin-2mg',
    shortDescription: 'High-purity lyophilized peptide for scientific research.',
    description: 'Tesamorelin 2mg is provided for research and human consumption, or therapeutic use.',
    format: 'Lyophilized Powder',
    price: 29,
    image: '/products/tesamorelin-2mg.png',
    category: 'Peptides',
    batchDataAvailable: true,
  }
,
  {
    id: '38',
    name: 'Alluvi Glow GHK-Cu – BPC-157 & TB-500 70mg',
    slug: 'alluvi-glow-ghk-cu-bpc-157-tb-500-70mg',
    shortDescription: 'High-purity peptide pen for scientific research.',
    description: 'Alluvi Glow GHK-Cu – BPC-157 & TB-500 70mg is provided for research and human consumption, or therapeutic use.',
    format: 'Peptide Pen',
    price: 89.99,
    image: '/products/pens/alluvi-glow-ghk-cu-bpc-157-tb-500-70mg.png',
    category: 'Alluvi',
    batchDataAvailable: true,
  },
  {
    id: '39',
    name: 'Alluvi NAD+ 1000mg',
    slug: 'alluvi-nad-1000mg',
    shortDescription: 'High-purity peptide pen for scientific research.',
    description: 'Alluvi NAD+ 1000mg is provided for research and human consumption, or therapeutic use.',
    format: 'Peptide Pen',
    price: 169.99,
    image: '/products/pens/alluvi-nad-1000mg.png',
    category: 'Alluvi',
    batchDataAvailable: true,
  },
  {
    id: '40',
    name: 'Alluvi Retatrutide 20mg (R&D)',
    slug: 'alluvi-retatrutide-20mg-r-d',
    shortDescription: 'High-purity peptide pen for scientific research.',
    description: 'Alluvi Retatrutide 20mg (R&D) is provided for research and human consumption, or therapeutic use.',
    format: 'Peptide Pen',
    price: 100,
    image: '/products/pens/alluvi-retatrutide-20mg-r-d.png',
    category: 'Alluvi',
    batchDataAvailable: true,
  },
  {
    id: '41',
    name: 'Alluvi Retatrutide 20mg ×2 Bundle',
    slug: 'alluvi-retatrutide-20mg-2-bundle',
    shortDescription: 'High-purity peptide pen for scientific research.',
    description: 'Alluvi Retatrutide 20mg ×2 Bundle is provided for research and human consumption, or therapeutic use.',
    format: 'Peptide Pen',
    price: 199.99,
    image: '/products/pens/alluvi-retatrutide-20mg-2-bundle.png',
    category: 'Alluvi',
    batchDataAvailable: true,
  },
  {
    id: '42',
    name: 'Alluvi Retatrutide 40mg',
    slug: 'alluvi-retatrutide-40mg',
    shortDescription: 'High-purity peptide pen for scientific research.',
    description: 'Alluvi Retatrutide 40mg is provided for research and human consumption, or therapeutic use.',
    format: 'Peptide Pen',
    price: 189.99,
    image: '/products/pens/alluvi-retatrutide-40mg.png',
    category: 'Alluvi',
    batchDataAvailable: true,
  },
  {
    id: '43',
    name: 'Alluvi Retatrutide 40mg ×2 Bundle',
    slug: 'alluvi-retatrutide-40mg-2-bundle',
    shortDescription: 'High-purity peptide pen for scientific research.',
    description: 'Alluvi Retatrutide 40mg ×2 Bundle is provided for research and human consumption, or therapeutic use.',
    format: 'Peptide Pen',
    price: 315,
    image: '/products/pens/alluvi-retatrutide-40mg-2-bundle.png',
    category: 'Alluvi',
    batchDataAvailable: true,
  },
  {
    id: '44',
    name: 'Alluvi Retatrutide BPC-157 & TB-500 40mg',
    slug: 'alluvi-retatrutide-bpc-157-tb-500-40mg',
    shortDescription: 'High-purity peptide pen for scientific research.',
    description: 'Alluvi Retatrutide BPC-157 & TB-500 40mg is provided for research and human consumption, or therapeutic use.',
    format: 'Peptide Pen',
    price: 139.99,
    image: '/products/pens/alluvi-retatrutide-bpc-157-tb-500-40mg.png',
    category: 'Alluvi',
    batchDataAvailable: true,
  },
  {
    id: '45',
    name: 'Alluvi Tirzepatide 20mg',
    slug: 'alluvi-tirzepatide-20mg',
    shortDescription: 'High-purity peptide pen for scientific research.',
    description: 'Alluvi Tirzepatide 20mg is provided for research and human consumption, or therapeutic use.',
    format: 'Peptide Pen',
    price: 79.99,
    image: '/products/pens/alluvi-tirzepatide-20mg.png',
    category: 'Alluvi',
    batchDataAvailable: true,
  },
  {
    id: '46',
    name: 'Alluvi Tirzepatide 40mg',
    slug: 'alluvi-tirzepatide-40mg',
    shortDescription: 'High-purity peptide pen for scientific research.',
    description: 'Alluvi Tirzepatide 40mg is provided for research and human consumption, or therapeutic use.',
    format: 'Peptide Pen',
    price: 119.99,
    image: '/products/pens/alluvi-tirzepatide-40mg.png',
    category: 'Alluvi',
    batchDataAvailable: true,
  },
  {
    id: '47',
    name: 'Retava GHK-Cu 50mg',
    slug: 'retava-ghk-cu-50mg',
    shortDescription: 'High-purity peptide pen for scientific research.',
    description: 'Retava GHK-Cu 50mg is provided for research and human consumption, or therapeutic use.',
    format: 'Peptide Pen',
    price: 100,
    image: '/products/pens/retava-ghk-cu-50mg.png',
    category: 'Reteva',
    batchDataAvailable: true,
  },
  {
    id: '48',
    name: 'Retava Retatrutide 10mg',
    slug: 'retava-retatrutide-10mg',
    shortDescription: 'High-purity peptide pen for scientific research.',
    description: 'Retava Retatrutide 10mg is provided for research and human consumption, or therapeutic use.',
    format: 'Peptide Pen',
    price: 150,
    image: '/products/pens/retava-retatrutide-10mg.jpeg',
    category: 'Reteva',
    batchDataAvailable: true,
  },
  {
    id: '49',
    name: 'Retava Retatrutide 30mg',
    slug: 'retava-retatrutide-30mg',
    shortDescription: 'High-purity peptide pen for scientific research.',
    description: 'Retava Retatrutide 30mg is provided for research and human consumption, or therapeutic use.',
    format: 'Peptide Pen',
    price: 320,
    image: '/products/pens/retava-retatrutide-30mg.jpeg',
    category: 'Reteva',
    batchDataAvailable: true,
  },
  {
    id: '50',
    name: 'Retava Tirzepatide 10mg',
    slug: 'retava-tirzepatide-10mg',
    shortDescription: 'High-purity peptide pen for scientific research.',
    description: 'Retava Tirzepatide 10mg is provided for research and human consumption, or therapeutic use.',
    format: 'Peptide Pen',
    price: 120,
    image: '/products/pens/retava-tirzepatide-10mg.png',
    category: 'Reteva',
    batchDataAvailable: true,
  },
  {
    id: '51',
    name: 'Retava Tirzepatide 30mg',
    slug: 'retava-tirzepatide-30mg',
    shortDescription: 'High-purity peptide pen for scientific research.',
    description: 'Retava Tirzepatide 30mg is provided for research and human consumption, or therapeutic use.',
    format: 'Peptide Pen',
    price: 290,
    image: '/products/pens/retava-tirzepatide-30mg.png',
    category: 'Reteva',
    batchDataAvailable: true,
  },
  {
    id: '52',
    name: 'Melanotan II (MT2) 10mg',
    slug: 'melanotan-ii-mt2-10mg',
    shortDescription: 'High-purity synthetic cyclic heptapeptide analog for scientific research.',
    description: 'Melanotan II (MT2) 10mg is supplied as high-purity lyophilized powder for research and human consumption, or therapeutic use.',
    format: 'Lyophilized Powder',
    price: 22.95,
    image: '/products/mt2-melanotan-ii-10mg.png',
    category: 'Peptides',
    batchDataAvailable: true,
  },
  {
    id: '53',
    name: 'Retatrutide 5mg',
    slug: 'retatrutide-5mg',
    shortDescription: 'Triple GIP/GLP-1/Glucagon receptor agonist research compound.',
    description: 'Retatrutide 5mg is supplied as high-purity lyophilized powder for research and human consumption, or therapeutic use.',
    format: 'Lyophilized Powder',
    price: 49.99,
    image: '/products/retatrutide-5mg.png',
    category: 'Peptides',
    batchDataAvailable: true,
  },
  {
    id: '54',
    name: 'Retatrutide 10mg',
    slug: 'retatrutide-10mg',
    shortDescription: 'Triple GIP/GLP-1/Glucagon receptor agonist research compound.',
    description: 'Retatrutide 10mg is supplied as high-purity lyophilized powder for research and human consumption, or therapeutic use.',
    format: 'Lyophilized Powder',
    price: 89.99,
    image: '/products/retatrutide-10mg.png',
    category: 'Peptides',
    batchDataAvailable: true,
  },
  {
    id: '55',
    name: 'Retatrutide 20mg',
    slug: 'retatrutide-20mg',
    shortDescription: 'Triple GIP/GLP-1/Glucagon receptor agonist research compound.',
    description: 'Retatrutide 20mg is supplied as high-purity lyophilized powder for research and human consumption, or therapeutic use.',
    format: 'Lyophilized Powder',
    price: 159.99,
    image: '/products/retatrutide-20mg.png',
    category: 'Peptides',
    batchDataAvailable: true,
  },
  {
    id: '56',
    name: 'Melanotan MT-2 10mg',
    slug: 'melanotan-mt2-10mg',
    shortDescription: 'Lyophilised research peptide vial for laboratory and analytical research settings.',
    description: 'Melanotan MT-2 10mg is supplied as a sterile lyophilised research peptide vial for laboratory, analytical, and scientific research use. Supplied in high-purity format with tracked dispatch and verified chain-of-custody handling.',
    format: 'Lyophilized Powder',
    price: 45,
    image: '/products/melanotan-mt2-10mg.webp',
    category: 'MT2',
    batchDataAvailable: true,
  }
];

export const featuredSlugs = [
  'retatrutide-10mg',
  'alluvi-retatrutide-20mg-r-d',
  'retava-retatrutide-10mg',
  'alluvi-tirzepatide-20mg',
  'retava-tirzepatide-10mg',
  'bpc-157-5mg',
  'thymosin-beta-4-5mg-tb500',
  'alluvi-glow-ghk-cu-bpc-157-tb-500-70mg',
  'retava-retatrutide-30mg',
  'alluvi-retatrutide-40mg',
  'retava-tirzepatide-30mg',
  'melanotan-ii-mt2-10mg',
  'ghk-cu-50mg-copper-peptide',
  'alluvi-retatrutide-bpc-157-tb-500-40mg',
  'retava-ghk-cu-50mg',
];

export const getFeaturedProducts = (count = 15): Product[] => {
  const featuredList: Product[] = [];
  for (const slug of featuredSlugs) {
    const p = products.find(prod => prod.slug === slug);
    if (p && !featuredList.some(item => item.id === p.id)) {
      featuredList.push(p);
    }
  }
  // Fill remaining if count exceeds specific list
  for (const p of products) {
    if (featuredList.length >= count) break;
    if (!featuredList.some(item => item.id === p.id)) {
      featuredList.push(p);
    }
  }
  return featuredList.slice(0, count);
};

export interface Article {
  id: string;
  title: string;
  slug: string;
  excerpt: string;
  date: string;
  author: string;
  category: string;
  image: string;
}

export const articles: Article[] = [
  {
    id: '1',
    title: 'Understanding Retatrutide: The Science of Triple Receptor Agonism',
    slug: 'understanding-retatrutide-science',
    excerpt: 'An in-depth look at how investigational compound retatrutide interacts with GLP-1, GIP, and Glucagon receptors in laboratory settings.',
    date: '2023-11-15',
    author: 'Dr. A. Scientist',
    category: 'Retatrutide',
    image: 'https://picsum.photos/seed/blog1/800/400',
  },
  {
    id: '2',
    title: 'How to Read a Certificate of Analysis (COA)',
    slug: 'how-to-read-coa',
    excerpt: 'A comprehensive guide to understanding HPLC purity reports, mass spectrometry data, and what they mean for peptide quality.',
    date: '2023-10-22',
    author: 'Analytical Team',
    category: 'Laboratory Testing',
    image: 'https://picsum.photos/seed/blog2/800/400',
  },
  {
    id: '3',
    title: 'Peptide Storage Principles: Maintaining Stability',
    slug: 'peptide-storage-principles',
    excerpt: 'Essential guidelines for storing lyophilized and reconstituted peptides to prevent degradation during research.',
    date: '2023-09-05',
    author: 'Lab Services',
    category: 'Peptide Education',
    image: 'https://picsum.photos/seed/blog3/800/400',
  }
];
